### PR TITLE
Add new GetMempoolEntry RPC method

### PR DESCRIPTION
**Pull request by lontivero**
Do not merge yet please, I want to improve a bit the properties' names

### CODE REVIEW

**Comment by nopara73** [comment]
Ohm, did you not look at my implementation? https://github.com/zkSNACKs/WalletWasabi/pull/936/files

**Comment by lontivero** [comment]
I'm on that @nopara73. I want to make it more NBitcoin-ish also.

**Comment by nopara73** [comment]
@lontivero Finished? If so I'll make a PR on this.

**Comment by lontivero** [comment]
Yes, I've finished with this.

**Comment by nopara73** [comment]
@lontivero How dare you leave out my beautiful XML comments? :D Ok, I'll make a new PR on top of this.

**Pull request closed without merging**
