### PR TITLE
GetEstimatedFee & TryGetEstimatedFee methods

### PR DESCRIPTION
**Pull request by lontivero**
This PR is for issue https://github.com/MetacoSA/NBitcoin/issues/209 and marks `EstimateFee` and `EstimateFeeAsync` as Obsolete methods. It also creates the three new methods:  `GetEstimatedFee`, `TryGetEstimatedFee`  and `GetEstimateFeeAsync`.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
just a nit, what about EstimateFeeRate and TryEstimateFeeRate, instead of get?

**Comment by NicolasDorier** [comment]
ha and InvalidOperationException should not be used.

`The following sections show how some common cases in which in InvalidOperationException exception is thrown in an app. How you handle the issue depends on the specific situation. Most commonly, however, the exception results from developer error, and the InvalidOperationException exception can be anticipated and avoided.`

But here it can't be anticipated by the dev. I would say, create a new excpetion in RPC namespace like EstimatedFeeNotFoundException()

**Comment by knocte** [comment]
> But here it can't be anticipated by the dev. I would say, create a new excpetion

Agreed.

> in RPC namespace like EstimatedFeeNotFoundException()

Is there any way to know the specific reason why it could not be estimated? If there are many possible reasons (instead of just one), ideally we would have different exception types for each.

**Comment by NicolasDorier** [comment]
@knocte  only reason is that Bitcoin Core does not have enough data for it. Maybe we should say it in error message.

**Comment by knocte** [comment]
Ok, but to not encourage ex.Message parsing, I would also add it on the exception name. Something like NotEnoughDataForEstimationException.

**Comment by NicolasDorier** [comment]
@knocte there is only one reason the fee can t be estimated

**Comment by NicolasDorier** [comment]
If it was not the case we would have details as prop of the exception,

**Comment by NicolasDorier** [comment]
or subclass of EstimatedFeeNotFoundException so we don t break existing code.

**Comment by knocte** [comment]
> or subclass of EstimatedFeeNotFoundException so we don t break existing code.

Ok but "estimated fee not found" doesn't seem correct wording. Either you can estimate or you cannot, but you don't "find" an estimation.

**Comment by knocte** [comment]
How about `EstimationNotPossibleException`

**Comment by NicolasDorier** [comment]
Strange, what about `NoEstimationException()` with error message saying "Try a lower estimation target or wait for Bitcoin Core to get more data."

**Comment by knocte** [comment]
Ok, sounds better than EstimatedFeeNotFound

**Pull request merged**
