### PR TITLE
Checking the block size (instead of length)

### PR DESCRIPTION
**Pull request by dangershony**
This is probably more correct

### CODE REVIEW

**Comment by NicolasDorier** [comment]
hey I will probably soon remove this code altogether as the consensus validation except the script evaluation part is quite out of date and not very tested.

I am implementing a full node here: https://github.com/stratisproject/StratisBitcoinFullNode/ which validate the consensus fully (segwit as well), it is a work in progress.

**Comment by NicolasDorier** [comment]
oh I'm stupid you are from Stratis ahah :D

**Comment by NicolasDorier** [comment]
removed the code on 3717631b, such code better belong to the full node project.

**Comment by dangershony** [comment]
It's outdated I see ok.
Yeah I am aware of the full node and you are currently working on the consensus but it will reference NBitcoin so I thought this was still valid.
In any case if its obsolete then ignore this pull

**Comment by NicolasDorier** [comment]
the only parts of the code concerning the consensus I'm happy on NBitcoin is the script evaluator and POW check. I'm using still NBitcoin for those two, the other rules, I redevelopped them from scratch for stratis full node.

**Pull request closed without merging**
