### PR TITLE
Update xunit.runner.visualstudio

### PR DESCRIPTION
**Pull request by nopara73**
Tests were not running. I updated the runner and now they are running properly.  

What I also tried:  

1. I installed .NET Framework development for VS, it still didn't work.

2. However I was able to make it work with the old runner version if I edited the following line in the test project's csproj:

```xml
<TargetFrameworks>net461;netcoreapp1.1</TargetFrameworks>
```

I added: `netcoreapp2.0` - did not work.  
I replaced `netcoreapp1.1` with `netcoreapp2.0` - did not work.  
I removed both `net461;netcoreapp1.1` and replaced with `netcoreapp2.0` - did work.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
so with `2.3.1` it works with both?

**Comment by NicolasDorier** [comment]
it makes sense to use netcoreapp2.0 now.

**Comment by nopara73** [comment]
With 2.3.1, everything works. Do you want me to add 2.0 or replace `1.1 with 2.0?

**Comment by NicolasDorier** [comment]
replace 1.1 with 2.0 and verify that 2.3.1 still work.

**Comment by nopara73** [comment]
@NicolasDorier  Replaced. Verified. Works.

**Pull request merged**
