### PR TITLE
Add method get list unspent with query_options

### PR DESCRIPTION
**Pull request by Ilchuk-Mihail**

### CODE REVIEW

**Comment by Ilchuk-Mihail** [comment]
For some reason - The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by knocte** [comment]
I think you should retry the build, the tests hang for about once every 10 times or so.

**Comment by knocte** [comment]
mmm still happening, so somehow this PR is making something fail on macOS; you would need to run it on your own to try to determine which of the tests is hanging

**Comment by NicolasDorier** [comment]
Can you use named parameter instead for passing RPC args?

**Comment by NicolasDorier** [comment]
Can you, instead of having an optional arguments, keeping the empty argument overload?

Because changing as optional args might will break stuff that got compiled with another version during runtime.

**Comment by Ilchuk-Mihail** [comment]
@NicolasDorier Not sure, if I understand you correctly. Can you please, add more detail ?

**Comment by NicolasDorier** [comment]
```csharp
public async Task<UnspentCoin[]> ListUnspentAsync();

public async Task<UnspentCoin[]> ListUnspentAsync(ListUnspentOptions options = null, params BitcoinAddress[] addresses);
```

If I call `rpcClient.ListUnspentAsync()` which one of those two get called? because it is ambiguous, it might break some code. Remove the `= null`

**Comment by Ilchuk-Mihail** [comment]
Ahhh ... Sorry, I missed that. But, very strange why the compiler is not issuing an error.

**Pull request merged**
