### PR TITLE
Reslove "Support for `wtxidrelay` message"

### LINKED ISSUE #1160: Support for `wtxidrelay` message
Bitcoin Core uses WTXID-based transaction relaying described in [BIP339](https://github.com/bitcoin/bips/blob/master/bip-0339.mediawiki). Support for this WTXID relaying is signalized during handshake (between `version` and `verack` messages) sending `wtxidrelay` message (without any payload). 

I suggest to add `wtxidrelay` message into supported [Payloads](https://github.com/MetacoSA/NBitcoin/tree/master/NBitcoin/Protocol/Payloads). 

NOTE:  The decisions based on receiving this massage, do not have to be implemented yet because it is only signaling message.

### PR DESCRIPTION
**Pull request by torx-cz**
Closes #1160

### CODE REVIEW

**Comment by torx-cz** [comment]
Please review @NicolasDorier .

**Comment by torx-cz** [comment]
Anything @NicolasDorier

**Comment by NicolasDorier** [comment]
hey thank you checking

**Comment by NicolasDorier** [comment]
Makign new version

**Comment by knocte** [comment]
> **Reslove** "Support for wtxidrelay message"

This should be the next big typo after hodl.

**Pull request merged**
