### PR TITLE
[WIP] Single project for .NET Core and .NET Framework assemblies

### PR DESCRIPTION
**Pull request by gertjaap**
Starting this for issue #255 

These project files compile properly on Visual Studio 2017 (outputs DLL's for .NET Framework 4.6.2, .NET Standard 1.1 and .NET Standard 1.3). I can also compile it using .NET Core command line on Mac (using --framework netstandard1.3 / 1.1).

Is this what we're looking for?

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Awesome testing

**Comment by NicolasDorier** [comment]
NBitcoin.Tests does not compile anymore it seems

**Comment by gertjaap** [comment]
I was still working on that - did this work before? First i was getting the error that Microsoft.TestPlatform.TestHost 15.0.0 is not compatible with netstandard1.3 (minimum 1.5), and when i upgraded to netstandard1.5 it was complaining about WebClient not being available.

**Comment by NicolasDorier** [comment]
@gertjaap fixing it

**Comment by NicolasDorier** [comment]
Thanks a lot, it was helpful. Making the tests pass was kind of a pain in the ass.

**Pull request merged**
