### PR TITLE
Update GSC filters to match bitcoin/bip158 PR

### PR DESCRIPTION
**Pull request by lontivero**
After some deep discussions in the bitcoin protocol dev mail list, there is a set of changes proposed in the follow [bitcoin/bip158 PR: https://github.com/bitcoin/bips/pull/687](https://github.com/bitcoin/bips/pull/687)

This commit contains the changes:

- Removes extended filter builder
- Removes TxID from basic filters
- Adds M parameter to customize the filter values range
- Updates test vectors (extended filters have been removed)

Once the [bitcoin/bip158 PR: https://github.com/bitcoin/bips/pull/687](https://github.com/bitcoin/bips/pull/687) is merged we can merge this PR into NBitcoin/master. **DO NOT MERGE BEFORE, THIS CAN CHANGE.**

### CODE REVIEW

**Comment by nopara73** [comment]
Is it going to be breaking change on our deployed systems?

**Comment by lontivero** [comment]
@nopara73 this new version contains changes in the filter parameters default values. That means we will need to make some small changes in our project in order to continue using the old parameters. However, the filter files don't need to be rebuilt.

**Comment by NicolasDorier** [comment]
ahah sorry I merged already ;)

No worry, will merge if there is a fix to do.

**Comment by nopara73** [comment]
@lontivero Can you make the changes in WalletWasabi? This would prevent us from updating NBitcoin.

**Pull request merged**
