### PR TITLE
Simplify DeterministicECDSA class

### PR DESCRIPTION
**Pull request by lontivero**
This PR is just to explain what I say in the issue #127. 
I replaced the current DeterministicECDSA class implementations with a thin wrapper around the BC ECDsaSigner and it works ok.

If you take a look at the new implementation (simplification), you will see that we hardly need this class because all what it does is already provided by BC.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
This is awesome, but why have have you removed some Assert.Equals in the tests in IETFDetailedExample ?

**Comment by lontivero** [comment]
I removed those asserts because this PR is just to show that BC already provides the mechanism for using hmac to have deterministic K values for signing. And given the DeterministicECDSA class is an _internal_ class that is used in only one place (ECKey class) my point is that we don't need this class and we could just delete it.

In other words: my idea is not simplify the class as I show in this PR, my idea is remove the class and that's why I didn't care about commenting those asserts.

Anyway, if you think this class worths, I can improve the code and keep the asserts. Just let me know.

**Comment by lontivero** [comment]
I've gave it a deeper look at the BC's ECDsaSigner class and it doesn't expose the LatsK and LastR values , sadly. I understand that's a problem for testeability reasons. However, given that the ECDsaSigner comes from a well-tested 3rd party library we could assume it works (as we do with the rest of the BC classes).

I also was thinking about delete the DeterministicECDSA class and now I think a better approach would be just use this simplified version (step nr 1) and then we could consider delete it if you agree with that (step nr 2).

**Comment by NicolasDorier** [comment]
We don't need the LastK and LastR but I'd like to keep the test.
```
Assert.Equal(test.S, ECDSASignature.FromDER(result).S);
```
I don't understand why I'm not also testing R, can you add.

```
Assert.Equal(test.R, ECDSASignature.FromDER(result).R);
```

Let's keep DeterministicECDSA with the implementation of BC as you did for now, and on a second pr delete it if we can. But I'd like to keep the test, because it is an important method.

**Pull request merged**
