### PR TITLE
Port seed data from bitcoin core 

### PR DESCRIPTION
**Pull request by lontivero**
Wasabi wallet users using Tail OS and similars (sorry I don't remember the names) cannot connect to the bitcoin p2p network because NBitcoin is not able to discover peers using the DNS seeds given that those systems cannot have access to the clear net, only Tor connections are possible.

One of those cases was the trigger to create this issue: https://github.com/MetacoSA/NBitcoin/issues/977 however, recently other users have reported a the problem that they cannot use Wasabi: https://github.com/zkSNACKs/WalletWasabi/issues/5512

NBitcoin uses two mechanism to bootstrap the initial list of node: 
* DNS seeds and,
* Fixed addresses

This PR simply imports the list of fixed addresses from bitcoin core which includes onion v2 and v3 addresses that can be used to connect to those and get more addresses.

@nopara73 is going to work in resolving dns lookups though Tor in case the application is using socks (Tor)

### CODE REVIEW

**Review by nopara73 — APPROVED** [review]
LGTM

**Comment by adamPetho** [comment]
The code LGTM, utACK

**Review by Szpoti — APPROVED** [review]
utACK, the code looks good

**Comment by gruve-p** [comment]
Hi @NicolasDorier 
Do the altcoins also need to update the seed data since the pnSeeds array is now converted differently?
I can send a PR to replace https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin.Altcoins/Groestlcoin.cs#L197-L283 with https://github.com/Groestlcoin/groestlcoin/blob/master/src/chainparamsseeds.h#L9-L104 

Please advice

**Comment by NicolasDorier** [comment]
I think altcoin does not need to update it if nobody uses it. Those seeds are used for a very specific case, which, as far as I know, only Wasabi ever needed.

**Pull request merged**
