### PR TITLE
Add Mogwaicoin

### PR DESCRIPTION
**Pull request by darkfriend77**
commented out neoscrypt for csharp
added mogwaicoin node download

### CODE REVIEW

**Comment by darkfriend77** [comment]
Okay, cleaned up code and all tests okay, except CanSyncWithoutPoW & CanSyncWithPoW ... they fail with InvalidOperationException("The node is not in a connected state") ...

**Comment by NicolasDorier** [comment]
`CanSyncWithoutPoW` should not fail.

**Comment by NicolasDorier** [comment]
Can you try to run the same tests on your machine but using Bitcoin instead of  Mogwaicoin?

This might be a dup of https://github.com/MetacoSA/NBitcoin/issues/502

**Comment by darkfriend77** [comment]
I did the same tests with Bitcoin and they succeed all .... Mogwaicoin Tests fail during node versionhandshake,

*var payload = listener.ReceivePayload<Payload>(cancellationToken);*

nodenotconnected00
nodenotconnected01
nodenotconnected02
nodenotconnected03png

**Comment by darkfriend77** [comment]
Okay somehow this code shows the same Node not connected error for bitcoin too ...
```
using NBitcoin.Tests;
using System;

namespace TestNode
{
    class Program
    {
        static void Main(string[] args)
        {
			using (var builder = NodeBuilderEx.Create())
			{
				Console.WriteLine(builder.Network.NetworkType);
				Console.WriteLine(builder.Network.NetworkSet);
				Console.ReadKey();
				var node = builder.CreateNode();
				builder.StartAll();
				var nodeClient = node.CreateNodeClient();
				nodeClient.VersionHandshake();
			}
		}
    }
}
 
```

image

**Comment by darkfriend77** [comment]
The versionhandshake fixed now, we had the magic bytes inverted.

CanSyncWithoutPoW still fails ...

Meldung: Assert.Equal() Failure
Expected: typeof(NBitcoin.BlockHeader)
Actual:   typeof(NBitcoin.Altcoins.Mogwai+MogwaiBlockHeader)

this seems a legit fail isn't it?

**Comment by NicolasDorier** [comment]
Remove `MogwaiBlockHeader`, you don't use it.

**Comment by darkfriend77** [comment]
```
		public class MogwaiBlockHeader : BlockHeader
		{
			// https://github.com/mogwaicoin/mogwai/blob/master/src/primitives/block.cpp
			static byte[] CalculateHash(byte[] data, int offset, int count)
			{
				var output = new byte[32];
				// reference https://github.com/mogwaicoin/NeoScryptCSharp for correct neoscrypt native c# hashing
				// haven't added source because it will need to have unsafe code checked for the project.
				NeoScrypt.NeoScrypt.neoscrypt(data, ref output, 0x0);
				return output;
			}

			protected override HashStreamBase CreateHashStream()
			{
				return BufferedHashStream.CreateFrom(CalculateHash);
			}

		}
```

**Comment by NicolasDorier** [comment]
It is not what you committed, sorry I don't have time to help you. Moreover, the test has a comment.

**Comment by darkfriend77** [comment]
It's okay you don't need to help I will fix it. For clarification, I have Neoscrypt C# implementation done, so I want to have all Test succeed. I think you wouldn't like unsafe code commited in a PR, that's why I have commented out Neoscrypt and removed the algo in my PR, but for my purpose I want to have it, of course removing MogwaiBlockHeader fix the test, but not if you I want to use the Neoscrypt algo. So I will do it like dash and readd the code to have CanSyncWithoutPoW succeed.

**Comment by NicolasDorier** [comment]
There is difference between PoWHash and BlockHash in some crypto currency.
If neoscrypt is only PoWHash, I advise you to not worry about `CanSyncWithPow`.

**Comment by darkfriend77** [comment]
For Mogwaicoin it is like Dash and for Dash all tests work, however we have hashPrevBlock & hashMerkleRoot as little endian in our blockheader not like dash and bitcoin big endian ... is there an easy way to change that. Then I think last test will succeed.

**Comment by kodxana** [comment]
@darkfriend77 Can you contact me on discord? Madiator2011#2793 i have some questions for you ;)

**Comment by NicolasDorier** [comment]
It is possible to fix, but I don't have time to tell you how nor to test your integration sorry :/

**Comment by darkfriend77** [comment]
You can merge it. It passes the tests.

https://github.com/MetacoSA/NBitcoin/pull/503#issuecomment-412061298

I will not worry about the CanSyncWithPoW :-)

**Pull request merged**
