### PR TITLE
Remove .NET Core files

### LINKED ISSUE #198: .NETCore solution does not load correctly.
After cloning the repo and clicking on `NBitcoin.NETCore.sln` I got this error message:  

> One or more projects in the solution were not loaded correctly.
> Please see the Output Window for details.

I click ok, then in the solution explorer under the `NBitcoin.NETCore.Tests` project:

> The project file or web cannot be found.

http://imgur.com/a/euNVK

Restoring the `NBitcoin` project and building it is successfull.
Although there are no sources under `NBitcoin` project in the solution explorer, but I think that is intentional, right? So you only use building the .NETCore project, not for developing, right?

Basically it looks for **`NBitcoin.NETCore.Tests\NBitcoin.NETCore.Tests.xproj`** file is missing, what is not under version control. It should solve the problem if you put push it.

### PR DESCRIPTION
**Pull request by nopara73**
I want to resolve #198 here.  
I added a these files and folders to the gitignore:  
- /NBitcoin.NETCore.sln  
- NBitcoin.NETCore.Tests  
- NBitcoin.NETCore  
  
Now there is an other issue that I am only 80% sure I am doing the GitHub workflow right. The UI is a confusing.  
What I want to do (If I remember correctly this is what @NicolasDorier told me half a year ago that would be the fine way to contribute):  
1. Create a branch on my fork for the work.  
2. Pull request that branch into the master of upstream.  
  
Would be great if someone could take a quick look that I am doing it right.

### CODE REVIEW

**Comment by nopara73** [comment]
I am doing something wrong. @knocte comment should not be here, neither my previous commits.  
Not sure what is happening, should I just delete my PR and fork and start it over or it is not so complicated to figure out what's going on and fix it?

**Comment by knocte** [comment]
Wow, you cloned a github comment from me, that is weird.

**Comment by NicolasDorier** [comment]
Only the SLN is not needed, the rest should stay.

**Comment by nopara73** [comment]
Why? 
By the way in that case you have to add the **NBitcoin.NETCore.Tests\NBitcoin.NETCore.Tests.xproj**.

**Comment by NicolasDorier** [comment]
if I accept your PR, then NBitcoin would not support .NETCOre on nugget anymore, why doing that?

**Comment by nopara73** [comment]
I thought your plan was to remove core altogether and you rather have it locally so you can build it for nuget.  
What is your goal with removing only the .sln file?

**Comment by NicolasDorier** [comment]
I don't want to remove Core support. I don't care about opening the core project into visual studio. I'm using it only in my building scripts for creating my nuget package with Core support.

**Comment by nopara73** [comment]
Makes sense now.  
So remove only the **.sln**.
Then how about removing the **.xproj** file from the **NBitcoin.NETCore** folder, too to be consinstent?

(Just to reiterate my original problem I opened the issue for was that I was not able to open properly the **.sln** file, because there were no **.xproj** file in **NBitcoin.Tests** folder, there is only an **.xproj** in **NBitcoin.NETCore** folder.)

**Comment by NicolasDorier** [comment]
yes we can remove both xproj and sln

**Comment by NicolasDorier** [comment]
I just nuked them https://github.com/MetacoSA/NBitcoin/commit/c051f8ca607ba539b8c3a39d13995c9759a8fcbf

**Pull request closed without merging**
