### PR TITLE
Fixed Dogecoin AuxPow header

### PR DESCRIPTION
**Pull request by bdangh**
Fixed Dogecoin chain synchronization issue because of hard-fork at 371337rd block.

https://github.com/dogecoin/dogecoin/blob/bb4b082c086689434d67490a15224c42fefdfd13/src/primitives/block.h#L38
https://github.com/dogecoin/dogecoin/blob/bb4b082c086689434d67490a15224c42fefdfd13/src/auxpow.h

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Cool!

**Comment by NicolasDorier** [comment]
Push 1.0.0.9. Let me know if it works, this is first time we try an altcoin with different header (@Kukks you might be interested)

**Comment by NicolasDorier** [comment]
Ping @dangershony you might like this

**Comment by Kukks** [comment]
Awesome! Seems like the issue is handled fine with this so far

**Comment by bdangh** [comment]
@NicolasDorier I tested it with mainnet node, all 2,175,500+ headers synchronized.

**Comment by NicolasDorier** [comment]
Super cool!

**Pull request merged**
