### PR TITLE
Implement mult batching

### PR DESCRIPTION
**Pull request by NicolasDorier**
image

(The horizontal axis is not at right scale.)

|    Method | KeyCount | Implementation |        Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|---------- |--------- |--------------- |------------:|----------:|----------:|---------:|---------:|---------:|----------:|
| BatchMult |        5 |           Auto |    473.7 us |   9.39 us |  17.18 us |   5.8594 |        - |        - |   43504 B |
| BatchMult |        5 |      Pippenger |    878.9 us |  15.57 us |  14.56 us |        - |        - |        - |     186 B |
| BatchMult |        5 |        Strauss |    462.4 us |   9.16 us |   8.99 us |   5.8594 |        - |        - |   43504 B |
| BatchMult |        5 |         Simple |    836.1 us |   8.18 us |   6.83 us |        - |        - |        - |     184 B |
| BatchMult |       20 |           Auto |  1,609.3 us |  30.81 us |  25.73 us |  15.6250 |   1.9531 |        - |  137404 B |
| BatchMult |       20 |      Pippenger |  2,195.7 us |  34.47 us |  30.56 us |        - |        - |        - |     197 B |
| BatchMult |       20 |        Strauss |  1,610.7 us |  27.10 us |  24.02 us |  15.6250 |   1.9531 |        - |  137395 B |
| BatchMult |       20 |         Simple |  3,359.6 us |  60.21 us |  50.28 us |        - |        - |        - |     184 B |
| BatchMult |       40 |           Auto |  3,214.3 us |  62.36 us |  81.08 us |  31.2500 |   7.8125 |        - |  274480 B |
| BatchMult |       40 |      Pippenger |  3,525.0 us |   7.79 us |   6.91 us |        - |        - |        - |     184 B |
| BatchMult |       40 |        Strauss |  3,155.7 us |  59.80 us |  58.74 us |  31.2500 |   7.8125 |        - |  274480 B |
| BatchMult |       40 |         Simple |  6,593.4 us |  94.19 us |  78.65 us |        - |        - |        - |     185 B |
| BatchMult |       80 |           Auto |  6,224.1 us |  54.58 us |  48.38 us | 140.6250 | 140.6250 | 140.6250 |  548646 B |
| BatchMult |       80 |      Pippenger |  6,008.2 us |  37.75 us |  31.52 us |        - |        - |        - |     184 B |
| BatchMult |       80 |        Strauss |  6,184.3 us |  73.36 us |  65.03 us | 132.8125 | 132.8125 | 132.8125 |  548646 B |
| BatchMult |       80 |         Simple | 13,376.5 us | 233.89 us | 207.34 us |        - |        - |        - |     188 B |
| BatchMult |       90 |           Auto |  6,681.5 us |  89.20 us |  83.44 us |        - |        - |        - |     184 B |
| BatchMult |       90 |      Pippenger |  6,644.3 us |  43.39 us |  36.23 us |        - |        - |        - |     184 B |
| BatchMult |       90 |        Strauss |  6,876.7 us |  41.35 us |  38.68 us | 132.8125 | 132.8125 | 132.8125 |  548646 B |
| BatchMult |       90 |         Simple | 15,083.2 us | 251.34 us | 258.10 us |        - |        - |        - |     184 B |
| BatchMult |      150 |           Auto |  9,892.7 us |  84.50 us |  70.56 us |        - |        - |        - |     184 B |
| BatchMult |      150 |      Pippenger | 10,069.0 us | 198.55 us | 203.90 us |        - |        - |        - |     184 B |
| BatchMult |      150 |        Strauss | 11,488.9 us |  86.72 us |  76.88 us | 250.0000 | 250.0000 | 250.0000 | 1097046 B |
| BatchMult |      150 |         Simple | 24,818.0 us | 296.95 us | 277.77 us |        - |        - |        - |     184 B |

|    Method | KeyCount | Implementation |        Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|---------- |--------- |--------------- |------------:|----------:|----------:|---------:|---------:|---------:|----------:|
| BatchMult |      300 |           Auto | 17.76 ms | 0.295 ms | 0.393 ms |        - |        - |        - |     184 B |
| BatchMult |      300 |      Pippenger | 17.21 ms | 0.190 ms | 0.178 ms |        - |        - |        - |     184 B |
| BatchMult |      300 |        Strauss | 23.21 ms | 0.365 ms | 0.324 ms | 468.7500 | 468.7500 | 468.7500 | 2193687 B |
| BatchMult |      300 |         Simple | 49.79 ms | 0.651 ms | 0.577 ms |        - |        - |        - |     629 B |
| BatchMult |      500 |           Auto | 26.35 ms | 0.478 ms | 0.424 ms |        - |        - |        - |     184 B |
| BatchMult |      500 |        Strauss | 37.87 ms | 0.278 ms | 0.260 ms | 428.5714 | 428.5714 | 428.5714 | 2193686 B |
| BatchMult |      500 |         Simple | 82.96 ms | 1.566 ms | 1.804 ms |        - |        - |        - |     184 B |

Ping @nopara73 

I will add an example on how to split on several CPU in the tests soon.

### CODE REVIEW

**Comment by nopara73** [comment]
@lontivero @nothingmuch @seresistvanandras can you guys take a look at this PR?

**Comment by NicolasDorier** [comment]
Merging and releasing new packages if you want to dogfood

**Comment by lontivero** [comment]
@NicolasDorier your numbers show a memory leak in the strauss implementation. It is because you are not disposing the strauss state after using it. I disposed it and this is how it looks like:

```
|    Method | KeyCount | Implementation |      Mean |    Error |    StdDev |    Median | Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |--------- |--------------- |----------:|---------:|----------:|----------:|------:|------:|------:|----------:|
| BatchMult |      300 |           Auto |  21.63 ms | 0.433 ms |  1.028 ms |  21.47 ms |     - |     - |     - |      24 B |
| BatchMult |      300 |      Pippenger |  21.69 ms | 0.431 ms |  0.919 ms |  21.45 ms |     - |     - |     - |      24 B |
| BatchMult |      300 |        Strauss |  27.91 ms | 0.511 ms |  1.066 ms |  27.72 ms |     - |     - |     - |      24 B |
| BatchMult |      300 |         Simple |  60.16 ms | 1.086 ms |  1.293 ms |  59.99 ms |     - |     - |     - |      24 B |
| BatchMult |      500 |           Auto |  32.70 ms | 0.650 ms |  0.667 ms |  32.66 ms |     - |     - |     - |      24 B |
| BatchMult |      500 |      Pippenger |  37.74 ms | 0.948 ms |  2.750 ms |  36.87 ms |     - |     - |     - |      24 B |
| BatchMult |      500 |        Strauss |  50.37 ms | 0.990 ms |  1.785 ms |  50.31 ms |     - |     - |     - |      24 B |
| BatchMult |      500 |         Simple | 112.84 ms | 3.524 ms | 10.224 ms | 109.61 ms |     - |     - |     - |      24 B |
```

No Gen{0|1|2}.

**Comment by NicolasDorier** [comment]
@lontivero awesome thanks will do another version then.

**Comment by NicolasDorier** [comment]
that said, not returning an array from the pool is not a leak. It is just less efficient than using `new`

**Comment by NicolasDorier** [comment]
@lontivero fixed. By curiosity do you have so much point to batch together for wabisabi??

**Comment by lontivero** [comment]
You're right, "leak" is not the correct term.  But it communicated the idea anyway ;)

> By curiosity do you have so much point to batch together for wabisabi??

Yes. I don't remember the exact number but yes. We have range proofs for 54bit numbers and three multiplications for each of them so, lets say we have more than 150 multiplications per range proof. Taking into account that we have normally two credential requests per httprequest then we have at least 300 multiplications.

**Comment by nothingmuch** [comment]
it's [3 generators per equation](https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs#L180-L243) so that's roughly the batch size (51 bits btw, not 54) , but there's more than one equation per range proof so there are multiple batches per range proof

**Comment by NicolasDorier** [comment]
Does the range proof you are using are ported from range proof from Elements/Liquid?

**Comment by NicolasDorier** [comment]
btw `test_ecmult_multi2` is showing an example of how to use multi core.
The bench are single core.

**Comment by nothingmuch** [comment]
> Does the range proof you are using are ported from range proof from Elements/Liquid?

no, only a very simple Sigma protocol, slightly fewer operations than Bulletproofs but much larger in size, and quite different from Borromean ring signatures

**Comment by nothingmuch** [comment]
(but they could be)

**Comment by NicolasDorier** [comment]
@nothingmuch would you need me to port borromean ring sig for wabisabi?

**Comment by nothingmuch** [comment]
I don't think there's a clear benefit, at least not at this point:

- Proof size is less of an issue, since they aren't kept (may affect
- Time complexity of BRS not likely to be better
- Conceptually harder to understand, so makes it harder for people to audit
themselves

Bulletproofs would make more of an impact, especially if general arithmetic
circuits are supported (not just range proofs) because then we could just
have one proof for all statements of a request.
But i think before we decide to add that complexity we should be sure that
it's not a solution looking for a problem

**Pull request merged**
