### PR TITLE
Magic byte - first byte duplicated bug fix (and test)

### PR DESCRIPTION
**Pull request by dangershony**

### CODE REVIEW

**Comment by dangershony** [comment]
This was discovered when reading the stratis blockchain blk0001.dat

**Comment by NicolasDorier** [comment]
thanks a lot, can you fix indents to tab ?

**Comment by NicolasDorier** [comment]
mmh, I don't think we should do that: ReadMagic is expected to read only the Magic and nothing else.

I think this should be fixed at the caller level. (BlockStore)

**Comment by NicolasDorier** [comment]
Oh you are right, nice finding, if you can just fix the indent I'll merge that now, thanks a lot!

**Comment by dangershony** [comment]
Done. 
VS acting funny with identity my code.

**Comment by dangershony** [comment]
By the way this probably explains why when parsing only block headers I had no missing blocks. 
The BlockStore class uses the block size field to skip the content, it probably jumped directly to the next magic byte.

**Comment by knocte** [comment]
Thanks for indenting the code.

Do you mind squashing your 3 commits into one? You can do that by typing `EDITOR=nano git rebase -i HEAD~3` then changing from "pick" to "s" the first word of the 2 lines from the last to commits, then merge all the commit messages into one.

Thanks

**Comment by NicolasDorier** [comment]
Alternatively you can change "pick" to "f" which remove the commit message of the squashed commits.

**Comment by dangershony** [comment]
Done (I think) this looks correct?

**Comment by knocte** [comment]
I see 5 commits now: https://github.com/MetacoSA/NBitcoin/pull/196/commits

What happened?

**Comment by dangershony** [comment]
Ha not sure, I squashed the last two commits (the indent commits) and then was asked to merge (not sure why as no commits where done since my branch was taken) any ideas?

**Comment by knocte** [comment]
@NicolasDorier I think github has now an option that lets you merge a PR by squashing all commits into one from the web UI, can you check?

**Comment by NicolasDorier** [comment]
oh yeah brilliant!

**Comment by dangershony** [comment]
Thanks @NicolasDorier and @knocte 
Any idea why my squash got messed up?

**Comment by NicolasDorier** [comment]
no idea, I've occasionally messed up squash with git (but it is rather rare normally).

I don't know how it can mess up as I don't see how it could create a conflict which need manual merge.

**Pull request merged**
