### PR TITLE
Add gitattributes file

### LINKED ISSUE #823: LineEnding issues
Seriously, what is wrong with this project?

setting git config to `autocrlf true` - as it is recommended by github results in all lines considered to be changed.

so i set `autocrlf false` and in my editor lines are ending with CRLF, but `git diff` and also github too show the line endings as changed. with the addition of an `^M` (which is a `CR`) suggesting that your files indeed use `LF` as line endings.

The `.editorconfig` specifies a line ending of `CRLF`.

a `.gitattributes` could be added to solve this mystery.

I'd be glad for some clarification.
Thanks

### PR DESCRIPTION
**Pull request by yahiheb**
Fixes #823

### CODE REVIEW

**Comment by knocte** [comment]
Why does Travis fail?

**Comment by nopara73** [comment]
Not because of this.

**Comment by knocte** [comment]
Would be great to get CI stable. Maybe converge to GithubActionsCI fixes it as a bonus?

**Comment by knocte** [comment]
(GithubActionsCI also supports macOS, which IIRC is not supported by neither AppVeyor nor Travis in the free tier.)

**Pull request merged**
