### PR TITLE
SLIP 21 and SLIP 77 (symmetric key derivation and blinding key derivation

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by Kukks** [comment]
@lontivero thanks for the review! This was mostly monkey ported from libwally and elementsd but will shortly make the refactoring you mentioned. I still figured out why the tests don't pass though. :(

**Comment by NicolasDorier** [comment]
@Kukks mind rebasing and see if it is still relevant?

**Comment by lontivero** [comment]
FTR. Wasabi implements slip21 here: https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Crypto/Slip21Node.cs

**Comment by Kukks** [comment]
@lontivero  Thanks for the tip. I've rebased and updated the PR as per your review.

@NicolasDorier  I think it is ready to merge now. Both SLIP 77 and SLIP21 tests pass correctly

**Pull request merged**
