### PR TITLE
Rename file (NBitcoin/UInt2561.cs -> NBitcoin/UInt256.cs)

### PR DESCRIPTION
**Pull request by yahiheb**
I don't know why the diff is crazy.
With Hide whitespace changes on https://github.com/MetacoSA/NBitcoin/pull/853/files?diff=unified&w=1

### CODE REVIEW

**Comment by NicolasDorier** [comment]
We should just remove this tt file.

**Comment by yahiheb** [comment]
> We should just remove this tt file.

Done, but I can't fix the conflicts.

**Comment by NicolasDorier** [comment]
just did it

**Comment by yahiheb** [comment]
> just did it

The tt file is still on master, and shouldn't we rename the UInt2561 file?

**Comment by NicolasDorier** [comment]
I did it; I think I messed up my merge before

**Pull request closed without merging**
