### PR TITLE
Added Dash

### PR DESCRIPTION
**Pull request by bdangh**
Added Dash with SHA3 crypto for X11 header hash calculation, Mainnet works fine.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Awesome! Can you add it to NBitcoin.TestFramework ? The "altcoins" tests are doing some very basic additional checks on regtest.

**Comment by NicolasDorier** [comment]
Ah you did! wonderful

**Comment by NicolasDorier** [comment]
System.Exception : Hash of downloaded file does not match (Expected: 19768b5395ce072387a2c130b65f4fdd6d7bf16a7cef88c0acfc46bd759201e2, Actual: 04e95d11443d785ad9d98b04fd2313ca96d937e424be80f639b73846304d154c)

They changed the file ?

**Comment by bdangh** [comment]
Most likely I copied wrong hash, I tested only mainnet with NBXplorer, will push that part tomorrow. Alao I’m not sure about PoW, will look into tomorrow too.

**Comment by NicolasDorier** [comment]
That's fine doing now! awesome job the tests pass

**Comment by NicolasDorier** [comment]
Pushed new version of NBitcoin.Altcoins and NBitcoin.TestFramework.

**Comment by bdangh** [comment]
Awesome, Thanks! I have one more coin coming soon, BitcoinGold. ConsensusFactory is incredible.

**Comment by lepipele** [comment]
@bdangh this looks awesome, great job!

**Pull request merged**
