### PR TITLE
UPDATED: Comments and messages only. Removed all code changes.

### PR DESCRIPTION
**Pull request by iainholder**
Update fixing some spelling and typos. Conservative changes, done mainly by hand. Two biggest single changes are zeroes -> zeros and advertize -> advertise (the only correct spelling in US and GB English). No changes from US->GB or GB->US.

### CODE REVIEW

**Comment by knocte** [comment]
> I would prefer if you could reverse the exception message fixes. Those can break applications.

I disagree with this, if someone is parsing exception messages they're doing it wrong and their application should break.

**Comment by NicolasDorier** [comment]
Yes, parsing messages is wrong. Also the errors he fixed are about exception happening only when your code has an obvious bug. (`ArgumentException`)

**Comment by nopara73** [comment]
"If a change results in user programs breaking, it's a bug in the kernel. We never EVER blame the user programs."

https://lkml.org/lkml/2012/12/23/75

**Comment by knocte** [comment]
I don't think that quote can be framed properly when someone changes a typo on an error message. The Linux kernel is written in C and probably all error codes are integer in that case...

**Comment by nopara73** [comment]
I think it's more important in Bitcoin. We're playing with people's money after all.

**Comment by nopara73** [comment]
I'm fine with breaking stuff only when Visual Studio complains. Of course this is a .net privilege, because linux gurus' command line cist editors won't tell them about anything. But let's not overdo it.

**Comment by knocte** [comment]
Parsing error messages is simply wrong. If you lose money because you use crappy software, it's the user's problem :) .NET has an exceptions model so if any library wants to consume errors and do different things depending on the error, they will need to make sure that the library they consume has different exception types for each error condition. E.g.: some months ago I found that key decription in Nethereum threw a generic "Exception" type message; instead of checking the exception's message from my wallet, what I did was a PR to Nethereum to change the exception being thrown by a new exception type just created for this purpose. This is how error handling works in .NET, if you do it differently you're doing it wrong ;-)

**Comment by nopara73** [comment]
@knocte It doesn't matter what is the best practice in consuming an API. What matters is what is the best practice in writing an API. Not changing the user space unless it is unavoidable is the best practice. We did not follow this best practice today, so what we did is "simply wrong."

**Comment by knocte** [comment]
I didn't explain best practices of consuming an API, I explained how error handling works in .NET, not a best practice, but the guideline. Anyway upgrading a dependency might always break things unless you have tests so if someone upgrades without testing or having tests, their workflow is also "simply wrong".

**Comment by NicolasDorier** [comment]
NBitcoin is mainly stable, I rarely break anything and what I break get ample time to migrate via `[Obsolete]` with proper migration tips that I remove after one or two years.

The exception message, while technically breaking, is so unlikely to happen that there is no need to bother about it. Especially that those errors are not runtime exception, those are error for invalid parameters. If your code is firing `ArgumentException` you already have a bug.

**Pull request merged**
