### PR TITLE
VerifyMessage method overloads

### PR DESCRIPTION
**Pull request by lontivero**
Provides method overloads for verifying raw (`byte[]`) messages with raw signatures in both, `BitcoinPubkeyAddress` and `BitcoinWitPubkeyAddress` as follow:

Currently (before this PR) we have one method:
```c#
public bool VerifyMessage(string message, string signature)
```

Proposed (after this PR) we have an overload:
```c#
public bool VerifyMessage(byte[] message, byte[] signature)
```

The PR also introduces a new interface to abstract both type of addresses given that they both have `VerifyMessage` method. @NicolasDorier please take a look at this and let me know your feedback.

Finally, the already-existing `CanVerifySignature` unit test was extended in order to include also a test for verifying signatures from bech32 addresses.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
no, there is @kallewoof who was working on something to make VerifyMessage more universal, but unsure how far he is. Will ask him.

**Comment by nopara73** [comment]
To be clear, we don't need that feature, I'm just curious.

**Comment by lontivero** [comment]
Just a comment about why it is not possible: Alice signs a message `m` with her private key `ka` such that `signature = ecdsa_sign(ka, m)`. ECDSA signature scheme allows us to recover the Alice's public key `Ka` from the signature and the message such that `Ka = ecdsa_recover_pubkey(signature, m)`. Now that we have the Alice's public key, we can check if the corresponding bitcoin address match with the Alice's address: `hash160(hash256(Ka)) == alice_address`.

The important point here is that we can recover the public key so, we can generate an address from it. We **cannot recover the script (neither its hash)** necessary for generating a p2sh address.

**Comment by NicolasDorier** [comment]
It is possible if you change the definition where "Verifying the signature" means "Providing a scriptSig/Witness solving the scriptPubKey"

**Comment by nopara73** [comment]
Quoting @SamouraiDev's explanation here: https://github.com/nopara73/ZeroLink/issues/45

> This can be done with p2sh wrapped segwit since the script format is known beforehand (as opposed to other p2sh). Pubkey is recovered from signature and used to derive p2sh-p2wpkh address.

**Comment by lontivero** [comment]
Ohhh I see. Then, something like this should work:

```c#
public bool VerifyMessage(string message, string signature)
{
	var key = PubKey.RecoverFromMessage(message, signature);
	return key.WitHash.ScriptPubKey.Hash == Hash;
}
```

Let try.

**Comment by nopara73** [comment]
Neat 😄

**Pull request merged**
