### PR TITLE
Fixing that Id should be increment when batching requests with certain RPC providers.

### PR DESCRIPTION
**Pull request by dlebee**
We are currently transitioning our RPCs to Chainstack. When multiple requests are combined into a single HTTP request, we ensure that each RPC request is assigned a unique ID.

### CODE REVIEW

**Review by marc-aurele-besner — APPROVED** [review]
LGTM 🚀 😂

**Comment by NicolasDorier** [comment]
@dlebee can you confirm if it works? Maybe the results come back unordered and something else need to change (unsure)

**Comment by dlebee** [comment]
I only confirmed its crashing, we had to use child class and reflection to fix it for now, so I can confirm tomorrow.

right now the batch code assumes the response come in the same order they are sent, so I assume the order should remain the same?

**Comment by NicolasDorier** [comment]
I think the assumption that the order is the same hold with a real bitcoin core, but fail with Chainstack. In such case, you should just order the responses based on the id.

**Pull request merged**
