### PR TITLE
Add KeyPath.TryParse

### PR DESCRIPTION
**Pull request by lontivero**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Raising exception is costly, can you instead refactor the `KeyPath.Parse` to use `KeyPath.TryParse`, and have `TryParse` do the actual parsing? Also still need parameter null exception if path is null.

**Comment by lontivero** [comment]
Sure

**Comment by NicolasDorier** [comment]
Making a new version, will do it

**Comment by ArtjomP** [comment]
Could you please update [QBitNinja](https://github.com/MetacoSA/QBitNinja) also. Because it doesn't compile with latest NBitcoin library.
Thank you in advance!

**Comment by NicolasDorier** [comment]
@ArtjomP yes, checking now

**Comment by NicolasDorier** [comment]
@ArtjomP done

**Comment by ArtjomP** [comment]
Thank you @NicolasDorier ! I appreciate this! Have a great day!

**Pull request merged**
