### PR TITLE
Adds support for Optical Bitcoin

### PR DESCRIPTION
**Pull request by hidaloop**
Info:
Optical Bitcoin is a fork of Bitcoin aiming to reduce mining energy consumption via compatibility with cutting edge optical compute cores.
For more information kindly refer to project's [GitHub Page](https://github.com/PoWx-Org).

Extra sources:
1. [PoWx](https://www.powx.org)
2. [HeavyHash paper](https://arxiv.org/pdf/1911.05193.pdf)
3. [Optical Bitcoin website](https://www.opticalbitcoin.org)
4. [BIP 0052](https://github.com/bitcoin/bips/blob/master/bip-0052.mediawiki)

Please note that this is an open source project, with fair (no pre-mine) start, and is open to contribution.

### CODE REVIEW

**Comment by hidaloop** [comment]
Hello! @NicolasDorier @Kukks
I am sorry for directly tagging you guys. I fully realize that none of you are interested in altcoins, and thus PR's of this kind are never a priority. However, I was hoping to understand if there is any updates or progress on this integration suggestion, or is it simply discarded, or just haven't had time to give it a look?

I would really appreciate it, if you could somehow inform of your thoughts on the pill request =)
Hope my message did not come across as impatient.

With kind regards, and respect
Anton.

**Comment by hidaloop** [comment]
@NicolasDorier do you copy?
Yet another attempt to reach you out. If there is any "behind the scenes" dynamics, please let me know.

**Comment by NicolasDorier** [comment]
behind the scene is that I am coming back from holiday

**Comment by NicolasDorier** [comment]
pushed on Altcoins 3.0.13

**Comment by hidaloop** [comment]
> behind the scene is that I am coming back from holiday

Ahaha, sorry for a message with impatient connotation =) Hope your holiday was great!

**Pull request merged**
