### PR TITLE
[WIP] Add `estimatesmartfee` RPC, deprecate `estimatefee` RPC

### PR DESCRIPTION
**Pull request by nopara73**
With Bitcoin Core 14.0 `estimatefee` is deprecated, instead `estimatesmartee` took its place.  

This PR is in WIP status, because I was not able to run the tests, due to the following error.  

```
[12/6/2017 6:12:45 PM Error] [xUnit.net 00:00:00.0636724] NBitcoin.Tests: Catastrophic failure: System.TypeInitializationException: The type initializer for 'Xunit.DiaSession' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Xunit.DiaSession..cctor()
   --- End of inner exception stack trace ---
   at Xunit.DiaSession..ctor(String assemblyFileName)
   at Xunit.DiaSessionWrapper..ctor(String assemblyFilename) in C:\projects\xunit\src\xunit.runner.utility\Utility\DiaSessionWrapper_DotNet.cs:line 16
   at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink) in C:\projects\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 64
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\projects\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 458
```

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Can you fix the conflict ?

**Comment by NicolasDorier** [comment]
@nopara73 I think the bitcoin core version to use for tests should be updated.

**Comment by nopara73** [comment]
@NicolasDorier Should I rename EstimateSmartFeeRate to EstimateSmartFee to stay near near from bitcoin naming?

**Comment by nopara73** [comment]
> @nopara73 I think the bitcoin core version to use for tests should be updated.  

It does not even hit the first line of the code.  It's not specific to RPC tests, all tests act the same.

In fact I have this strange red x here:


I will investigate this issue. It looks like not something you are aware of.

**Comment by nopara73** [comment]
I suspect it's because .NET Framework VS is not installed for me. In fact the target framework on project properties is empty for me. I will install it.

**Comment by NicolasDorier** [comment]
@nopara73 yes try to stay near of bitcoin naming convention.

**Pull request merged**
