### PR TITLE
xunit upgraded to v2.1.0

### PR DESCRIPTION
**Pull request by andbene72**
-PropertyData -> MemberData
-Assert.DoesNotThrow not needed because an exception is a failed test [https://github.com/xunit/xunit/issues/188](https://github.com/xunit/xunit/issues/188)
-Unused references removed (ProtocolBuffer...)

### CODE REVIEW

**Comment by NicolasDorier** [comment]
thanks can you remove the binaries from package completely instead of updating them ? I'm surprised I commited them.

**Comment by NicolasDorier** [comment]
ah sorry that's already the case good

**Comment by NicolasDorier** [comment]
For information I was not sure about updating to 2.1.0, because I have problems with my continuous integration server. Very often the tests don't want to run for mysterious reason, it is a bug that happens only above 2.0, and nothing has been done since several years about it.

**Comment by NicolasDorier** [comment]
image

**Comment by NicolasDorier** [comment]
For info, this is the bug I have on several build time to time above 2.0:

image

**Comment by andbene72** [comment]
I think can be this https://github.com/xunit/xunit/issues/261
solution is to upgrade nuget on the integration server.

Anyway I see that I have also to update the portable solution so if you prefer you can revert this commit, but I think it's not a long term solution, especially if it's a matter of "package supports frameworks that your version of NuGet doesn't know about. " as stated in the xunit issue.

**Comment by NicolasDorier** [comment]
I updated nuget now:

image

**Comment by NicolasDorier** [comment]
I will reverse this commit for now.

**Comment by andbene72** [comment]
OK.
Googling I found that 
> xunit.dll is for v1, and xunit.execution.desktop.dll is for v2.
I can speculate that somewhere there is a v1 reference.

**Comment by NicolasDorier** [comment]
I reversed it as well as pushed some of my outgoing commit, be carefull you'll probably need to rebase.

**Comment by NicolasDorier** [comment]
Here is the line for running the console tests:

> C:\Xunit\xunit.console.clr4.x86.exe NBitcoin.Tests/bin/Release/NBitcoin.Tests.exe /trait Core=Core /trait UnitTest=UnitTest /trait RPCClient=RPCClient /trait TestNet=TestNet /trait MainNet=MainNet /trait RestClient=RestClient

If you can make a PR which make it works will be happy to merge

**Comment by NicolasDorier** [comment]
oh wait, maybe the problem comes from me using the xunit v1 console app

**Comment by NicolasDorier** [comment]
you deleted your repo, I can't try your commit anymore, I think the problem came I was using wrong version of the console xunit runner, can you get the commit again ?

**Comment by andbene72** [comment]
Just a moment that I'm fixing portable test :)

**Comment by NicolasDorier** [comment]
I'm going to bed (2am here) will take a look tomorrow, don't forget to rebase as I pushed some commit.

**Comment by andbene72** [comment]
Ok, good night.

**Comment by andbene72** [comment]
Follow here https://github.com/MetacoSA/NBitcoin/pull/147

**Pull request merged**
