### PR TITLE
Feathercoin Support

### PR DESCRIPTION
**Pull request by ChekaZ**
Initial Support for Feathercoin.
- GetPoWHash() needs to be updated later on and switched to Neoscrypt.

### CODE REVIEW

**Comment by ChekaZ** [comment]
Trying right now, but some problems occured, will notify when they are cleared.

**Comment by NicolasDorier** [comment]
```
[DllImport("NBitcoin\\lib\\NeoScrypt.dll", EntryPoint = "neoscrypt_export", CallingConvention = CallingConvention.Cdecl)]
public static extern unsafe int neoscrypt(byte* input, byte* output, uint inputLength, uint profile);
```

Sorry, but don't use this. I don't want to depend on some native library. Either leave out the PoW implementation or do it is CSharp.

**Comment by ChekaZ** [comment]
Sure will reverse it, and also stall this request as Feathercoin hasnt got a working RegTest right now.

So its closed at this state as I cant perform all tests.

**Comment by ChekaZ** [comment]
Feathercoin hasnt got a working RegTest right now. So I cant perform all tests, will perform a new PR when its solved.

**Pull request closed without merging**
