### PR TITLE
[WIP] Re-enable Bitcoin Core consensus library

### PR DESCRIPTION
**Pull request by lontivero**
This is a work-in-progress PR for re-enabling the Bitcoin Core Consensus library. It needs review and test on Windows and OSX.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
interesting

```
[39;49m[39;49m[31m   at NBitcoin.Script.VerifyScriptConsensus(Byte[] scriptPubKey, UInt32 scriptPubKeyLen, Byte[] txTo, UInt32 txToLen, UInt32 nIn, ScriptVerify flags, BitcoinConsensusError& err)

   at NBitcoin.Script.VerifyScriptConsensus(Script scriptPubKey, Transaction tx, UInt32 nIn, ScriptVerify flags, BitcoinConsensusError& err) in /Users/travis/build/MetacoSA/NBitcoin/NBitcoin/Script.cs:line 928

   at NBitcoin.Tests.script_tests.AssertValidScript(Script scriptPubKey, Transaction tx, Int32 n, ScriptVerify verify) in /Users/travis/build/MetacoSA/NBitcoin/NBitcoin.Tests/script_tests.cs:line 763

   at NBitcoin.Tests.script_tests.script_CHECKMULTISIG23() in /Users/travis/build/MetacoSA/NBitcoin/NBitcoin.Tests/script_tests.cs:line 718

[39;49m[39;49m[31m[xUnit.net 00:03:30.1022790]     NBitcoin.Tests.script_tests.script_json_tests [FAIL]

[39;49m[39;49m[31m[xUnit.net 00:03:30.1161580]     NBitcoin.Tests.script_tests.script_CHECKMULTISIG12 [FAIL]

[39;49m[39;49m[31mFailed   NBitcoin.Tests.script_tests.script_json_tests

[39;49m[39;49m[31mError Message:

[39;49m[39;49m[31m System.EntryPointNotFoundException : Unable to find an entry point named 'bitcoinconsensus_verify_script_with_amount' in shared library 'libbitcoinconsensus'.

[39;49m[39;49m[31mStack Trace:

[39;49m[39;49m[31m   at NBitcoin.Script.VerifyScriptConsensusWithAmount(Byte[] scriptPubKey, UInt32 scriptPubKeyLen, Int64 amount, Byte[] txTo, UInt32 txToLen, UInt32 nIn, ScriptVerify flags, BitcoinConsensusError& err)

   at NBitcoin.Script.VerifyScriptConsensus(Script scriptPubKey, Transaction tx, UInt32 nIn, Money amount, ScriptVerify flags, BitcoinConsensusError& err) in /Users/travis/build/MetacoSA/NBitcoin/NBitcoin/Script.cs:line 937

   at NBitcoin.Tests.script_tests.AssertVerifyScript(WitScript wit, Money amount, Script scriptSig, Script scriptPubKey, ScriptVerify flags, Int32 testIndex, String comment, ScriptError expectedError) in /Users/travis/build/MetacoSA/NBitcoin/NBitcoin.Tests/script_tests.cs:line 385

   at NBitcoin.Tests.script_tests.script_json_tests() in /Users/travis/build/MetacoSA/NBitcoin/NBitcoin.Tests/script_tests.cs:line 367
```

Does it means it find the library but not the function?

**Comment by lontivero** [comment]
@NicolasDorier I was trying with different ideas to fix this problem. However, the error message is clear: it finds the .dylib file (otherwise the exception should be `DllNotFoundException`) but the **functions** (entry points** are not found. I didn't found a way to dump the .dylib symbols in order to see wheter those functions are there or not.

As you can see, it works for **Windows** and **Linux** (not in **OSX**). Do you have any suggestion? 
Could we disable this for _OSX_ and allow this for Windows and Linux? after all, this is a step forward compared with the current situation (consensus library is disabled)

**Comment by NicolasDorier** [comment]
You say it works on linux, but it seems that both build job are failing on travis?

**Comment by NicolasDorier** [comment]
I am unsure if it help: https://developer.rhino3d.com/guides/rhinocommon/wrapping-native-libraries/

That said, let's make it works for Windows and Linux.

**Comment by NicolasDorier** [comment]
Other suggestion: default CallingConvention might be different on mac os? Try set it explicitly

**Comment by lontivero** [comment]
I've reverted the last commit and now it fails only for OSX.

**Comment by NicolasDorier** [comment]
Can you disable the tests for OSX and put a `//TODO:`  ? NOw is better than nothing.

**Comment by lontivero** [comment]
Sure, that's the plan. I am implementing the Schnorr signatures batch verification now and I also have to add some extra methods to the blinding signature classes before taking this issue again. But it is just a matter of time and priorities.

**Comment by lontivero** [comment]
Sure, that's the plan. I am implementing the Schnorr signatures batch verification now and I also have to add some extra methods to the blinding signature classes before taking this issue again. But it is just a matter of time and priorities.

**Comment by lontivero** [comment]
Done.

**Comment by knocte** [comment]
@lontivero why is Travis failing now(macOS)? I thought OSX's test was disabled?

**Pull request merged**
