### PR TITLE
Allow setting sequence numbers of inputs with TransactionBuilder

### LINKED ISSUE #973: Feature request: Add ability to set sequence number of inputs on TransactionBuilder
Currently there's no way (as far as I can tell) to set the sequence number of a txin when building a transaction using `TransactionBuilder`, beyond setting it to `OptInRBF`. It might be nice to have a method like `TransactionBuilder.AddCoinWithSequence(ICoin coin, Sequence sequence)` or perhaps extend `Coin` itself with a `Sequence` field, or perhaps extend the API in some other way to achieve the same thing.

I'm happy to implement this myself but I'd like to hear opinions first on what the most appropriate way would be.

### PR DESCRIPTION
**Pull request by canndrew**
This PR adds a new `CoinOptions` type defined as:

```csharp
public class CoinOptions
{
	public CoinOptions()
	{
		Sequence = null;
	}

	public Sequence? Sequence;
}
```

As well a new `AddCoin` method to `TransactionBuilder` which takes an additional `CoinOptions` argument. This allows setting the sequence number on transaction inputs.

Fixes #973

### CODE REVIEW

**Comment by knocte** [comment]
@NicolasDorier any clue about why the CI timed out here?

**Comment by NicolasDorier** [comment]
No idea, but probably a bug in this PR.
This also need tests

**Comment by canndrew** [comment]
Tests are passing for this now, except for one of the pipelines though that appears to be a random failure unrelated to the PR.

**Comment by knocte** [comment]
The test failure seems indeed unrelated:

```
[xUnit.net 00:03:42.20]         /home/runner/work/NBitcoin/NBitcoin/NBitcoin.Tests/ProtocolTests.cs(702,0): at NBitcoin.Tests.ProtocolTests.CanConnectToRandomNode()
  X NBitcoin.Tests.ProtocolTests.CanConnectToRandomNode [27s 138ms]
  Error Message:
   System.InvalidOperationException : The node is not in a connected state
  Stack Trace:
     at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken) in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Protocol/NodeListener.cs:line 69
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken) in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Protocol/Node.cs:line 1045
   at NBitcoin.Protocol.Node.VersionHandshake(CancellationToken cancellationToken) in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Protocol/Node.cs:line 1034
   at NBitcoin.Tests.ProtocolTests.CanConnectToRandomNode() in /home/runner/work/NBitcoin/NBitcoin/NBitcoin.Tests/ProtocolTests.cs:line 702
```

Maybe this test should be retried several times in the test suite? So long as it can connect once successfully, it should pass.

@NicolasDorier can you review/merge?

**Comment by NicolasDorier** [comment]
Awesome, merging. I will change 2 or 3 things about it but that's great.

**Comment by NicolasDorier** [comment]
I released 5.0.74

**Pull request merged**
