### PR TITLE
NullFail exception when Finalizing PSBT

### PR DESCRIPTION
**Pull request by molnard**
I got a NullFail exception when trying to finalize a signed PSBT from Ledger device. In this PR I added a failing test.

Steps that I made:

1. Building a tx with 2 inputs and one output. One input is from a 2 ppl CoinJoin.
2. Sending the tx to Ledger.
3. Confirm on the device.
4. According to the device, everything is alright.
5. NBitcoin cannot finalize the tx. 

Related: https://github.com/zkSNACKs/WalletWasabi/issues/3995 https://github.com/MetacoSA/NBitcoin/issues/887

@nopara73 

### UPDATE! It doesn't matter if the inputs are from CoinJoin or not. If there are multiple inputs then it will fail. 

Also if I build a tx with exactly the same inputs and output but exclude the input txs from the PSBT, then the tx can be finalized and all good. 

[testtx_no_inputtxs.json.txt](https://github.com/MetacoSA/NBitcoin/files/4966109/testtx_no_inputtxs.json.txt)
[testtx_yes_inputtxs.json.txt](https://github.com/MetacoSA/NBitcoin/files/4966110/testtx_yes_inputtxs.json.txt)

### CODE REVIEW

**Comment by molnard** [comment]
Tx with non-coinjoin inputs. 2 inputs 1 output the simplest possible

```
{{
  "fee": "0.00000178 BTC",
  "feeRate": "1 Sat/B",
  "tx": {
    "hash": "c0f713f94aa7e83393c19fe3e52edb97e3a8bc8ebc227e43548de87660098666",
    "ver": 1,
    "vin_sz": 2,
    "vout_sz": 1,
    "lock_time": 0,
    "size": 123,
    "in": [
      {
        "prev_out": {
          "hash": "e74dfeed4131c14264807b4782f0a2b9a8a6413d1d3dd99fd85bd0bdf7cd7d02",
          "n": 0
        },
        "scriptSig": ""
      },
      {
        "prev_out": {
          "hash": "5a26baff403c678a8386a04800f82a693c12c9e5f8fc443492deb08e3cecbb15",
          "n": 0
        },
        "scriptSig": ""
      }
    ],
    "out": [
      {
        "value": "0.16185575",
        "scriptPubKey": "0 69a970f131b7044eca43256f8e1432c7963a7c2a"
      }
    ]
  },
  "inputs": [
    {
      "index": 0,
      "partial_signatures": {
        "022c9a180435eb0c83f35b30ce9ab61e59f4c94cb1c1e09c9ba30d552e45d2aa79": "30440220330aaaa74ffa3f02b6ef376d6208f35cb9afd83213f15134f4a9a5b355b16f460220663365b9e0da7ea2a7b6a0454af93c3615a929a08af35b9e50af64dd225ab1aa01"
      },
      "non_witness_utxo": {
        "hash": "e74dfeed4131c14264807b4782f0a2b9a8a6413d1d3dd99fd85bd0bdf7cd7d02",
        "ver": 1,
        "vin_sz": 1,
        "vout_sz": 1,
        "lock_time": 1781441,
        "size": 82,
        "in": [
          {
            "prev_out": {
              "hash": "321bee4fc64563709b4ee01715b925179c104bc349d1eb84e7a138dcd044ef6c",
              "n": 2
            },
            "scriptSig": "",
            "sequence": 4294967294
          }
        ],
        "out": [
          {
            "value": "0.11229088",
            "scriptPubKey": "0 c6236ab9791ad86a26deb50bc9154ecd554bf306"
          }
        ]
      },
      "witness_utxo": {
        "value": "0.11229088",
        "scriptPubKey": "0 c6236ab9791ad86a26deb50bc9154ecd554bf306"
      },
      "bip32_derivs": [
        {
          "pubkey": "022c9a180435eb0c83f35b30ce9ab61e59f4c94cb1c1e09c9ba30d552e45d2aa79",
          "master_fingerprint": "a573b895",
          "path": "84'/0'/0'/0/10"
        }
      ]
    },
    {
      "index": 1,
      "partial_signatures": {
        "0226faf9bd354f27a539176ee5a7969127751abf6b46be2f1dd4d5aa72dbde130e": "3044022063143e86822a822b22f97468d13763f09844f0a3333eabb583f501dd16535703022055a826a105f40474d3fa0386dcd64addcba288c2950997fa817aeef6822e1a5901"
      },
      "non_witness_utxo": {
        "hash": "5a26baff403c678a8386a04800f82a693c12c9e5f8fc443492deb08e3cecbb15",
        "ver": 1,
        "vin_sz": 1,
        "vout_sz": 1,
        "lock_time": 0,
        "size": 82,
        "in": [
          {
            "prev_out": {
              "hash": "ac65e533a94733184e61a71a1269c77775bca514edd285499590f3c763cb7a1b",
              "n": 2
            },
            "scriptSig": ""
          }
        ],
        "out": [
          {
            "value": "0.04956665",
            "scriptPubKey": "0 df741e7638513c0582a754ac0eb20189a5f0d704"
          }
        ]
      },
      "witness_utxo": {
        "value": "0.04956665",
        "scriptPubKey": "0 df741e7638513c0582a754ac0eb20189a5f0d704"
      },
      "bip32_derivs": [
        {
          "pubkey": "0226faf9bd354f27a539176ee5a7969127751abf6b46be2f1dd4d5aa72dbde130e",
          "master_fingerprint": "a573b895",
          "path": "84'/0'/0'/0/11"
        }
      ]
    }
  ],
  "outputs": [
    {
      "bip32_derivs": [
        {
          "pubkey": "03d5b9fab45a1c0287350a6d4d9b8daf5a5ba74d475d3c0faf2a354651a249de89",
          "master_fingerprint": "a573b895",
          "path": "84'/0'/0'/0/12"
        }
      ]
    }
  ]
}}
```

`cHNidP8BAHsBAAAAAgJ9zfe90FvYn9k9HT1Bpqi5ovCCR3uAZELBMUHt/k3nAAAAAAD/////FbvsPI6w3pI0RPz45ckSPGkq+ABIoIaDimc8QP+6JloAAAAAAP////8B5/j2AAAAAAAWABRpqXDxMbcETspDJW+OFDLHljp8KgAAAAAAAQEfoFerAAAAAAAWABTGI2q5eRrYaibetQvJFU7NVUvzBgEAUgEAAAABbO9E0Nw4oeeE69FJw0sQnBcluRUX4E6bcGNFxk/uGzICAAAAAP7///8BoFerAAAAAAAWABTGI2q5eRrYaibetQvJFU7NVUvzBsEuGwAiAgIsmhgENesMg/NbMM6ath5Z9MlMscHgnJujDVUuRdKqeUcwRAIgMwqqp0/6PwK27zdtYgjzXLmv2DIT8VE09Kmls1Wxb0YCIGYzZbng2n6ip7agRUr5PDYVqSmgivNbnlCvZN0iWrGqASIGAiyaGAQ16wyD81swzpq2Hln0yUyxweCcm6MNVS5F0qp5GKVzuJVUAACAAAAAgAAAAIAAAAAACgAAAAABAR/5oUsAAAAAABYAFN90HnY4UTwFgqdUrA6yAYml8NcEAQBSAQAAAAEbestjx/OQlUmF0u0Upbx1d8dpEhqnYU4YM0epM+VlrAIAAAAA/////wH5oUsAAAAAABYAFN90HnY4UTwFgqdUrA6yAYml8NcEAAAAACICAib6+b01TyelORdu5aeWkSd1Gr9rRr4vHdTVqnLb3hMORzBEAiBjFD6GgiqCKyL5dGjRN2PwmETwozM+q7WD9QHdFlNXAwIgVagmoQX0BHTT+gOG3NZK3cuiiMKVCZf6gXru9oIuGlkBIgYCJvr5vTVPJ6U5F27lp5aRJ3Uav2tGvi8d1NWqctveEw4YpXO4lVQAAIAAAACAAAAAgAAAAAALAAAAACICA9W5+rRaHAKHNQptTZuNr1pbp01HXTwPryo1RlGiSd6JGKVzuJVUAACAAAAAgAAAAIAAAAAADAAAAAA=`

**Comment by NicolasDorier** [comment]
Nullfail means that the signature is not valid. It may happen if you signed with the wrong key.

For ledger to fail signing correctly, I guess your PSBT is incorrect. (for example, keypath wrong or input wrong)

**Comment by nopara73** [comment]
Yes, it seems like that.

Our investigation found that when

- Ledger signs only 1 input tx, then it gives back `"final_script_witness"` and that can be finalized well.
- Ledger signs > 1 inputs tx, then it gives back `"partial_signatures"` what you can see in the json @molnard inserted and that tx cannot be finalized well. The evaluation of the final signed tx's input signatures fail.
- However if we don't provide inputs in the PSBT then (with the warning on the Ledger of course) then it gives back `"final_script_witness"` and that can be finalized well.

So the question is why does Ledger gives us `"partial_signatures"` when > 1 inputs are in the tx and can that be worked with or it cannot be worked with and Ledger must correct its issue.

**Comment by NicolasDorier** [comment]
This show that the signature is incorrect:

```csharp
var signed = PSBT.Parse("cHNidP8BAHsBAAAAAgJ9zfe90FvYn9k9HT1Bpqi5ovCCR3uAZELBMUHt/k3nAAAAAAD/////FbvsPI6w3pI0RPz45ckSPGkq+ABIoIaDimc8QP+6JloAAAAAAP////8B5/j2AAAAAAAWABRpqXDxMbcETspDJW+OFDLHljp8KgAAAAAAAQEfoFerAAAAAAAWABTGI2q5eRrYaibetQvJFU7NVUvzBgEAUgEAAAABbO9E0Nw4oeeE69FJw0sQnBcluRUX4E6bcGNFxk/uGzICAAAAAP7///8BoFerAAAAAAAWABTGI2q5eRrYaibetQvJFU7NVUvzBsEuGwAiAgIsmhgENesMg/NbMM6ath5Z9MlMscHgnJujDVUuRdKqeUcwRAIgMwqqp0/6PwK27zdtYgjzXLmv2DIT8VE09Kmls1Wxb0YCIGYzZbng2n6ip7agRUr5PDYVqSmgivNbnlCvZN0iWrGqASIGAiyaGAQ16wyD81swzpq2Hln0yUyxweCcm6MNVS5F0qp5GKVzuJVUAACAAAAAgAAAAIAAAAAACgAAAAABAR/5oUsAAAAAABYAFN90HnY4UTwFgqdUrA6yAYml8NcEAQBSAQAAAAEbestjx/OQlUmF0u0Upbx1d8dpEhqnYU4YM0epM+VlrAIAAAAA/////wH5oUsAAAAAABYAFN90HnY4UTwFgqdUrA6yAYml8NcEAAAAACICAib6+b01TyelORdu5aeWkSd1Gr9rRr4vHdTVqnLb3hMORzBEAiBjFD6GgiqCKyL5dGjRN2PwmETwozM+q7WD9QHdFlNXAwIgVagmoQX0BHTT+gOG3NZK3cuiiMKVCZf6gXru9oIuGlkBIgYCJvr5vTVPJ6U5F27lp5aRJ3Uav2tGvi8d1NWqctveEw4YpXO4lVQAAIAAAACAAAAAgAAAAAALAAAAACICA9W5+rRaHAKHNQptTZuNr1pbp01HXTwPryo1RlGiSd6JGKVzuJVUAACAAAAAgAAAAIAAAAAADAAAAAA=", Network.TestNet);

var global = signed.GetGlobalTransaction();
var pubkey = new PubKey("0226faf9bd354f27a539176ee5a7969127751abf6b46be2f1dd4d5aa72dbde130e");
var coin = new Coin(OutPoint.Parse("5a26baff403c678a8386a04800f82a693c12c9e5f8fc443492deb08e3cecbb15-0"), new TxOut(Money.Coins(0.04956665m), new Script("0 df741e7638513c0582a754ac0eb20189a5f0d704")));
var sigHash = global.GetSignatureHash(coin);
var signature = ECDSASignature.FromDER(Encoders.Hex.DecodeData("3044022063143e86822a822b22f97468d13763f09844f0a3333eabb583f501dd16535703022055a826a105f40474d3fa0386dcd64addcba288c2950997fa817aeef6822e1a5901"));
var sig = pubkey.Verify(sigHash, signature);
```

**Comment by NicolasDorier** [comment]
You should try without the non_witness_utxo

**Comment by molnard** [comment]
Excluded the input txs and ledger gives back this which was successfully finalized

```
{{
  "fee": "0.00000178 BTC",
  "feeRate": "1 Sat/B",
  "tx": {
    "hash": "d1e7d70e538d5bf0152a905afc1019557e0a6e29f9280f007c638fecd86ea887",
    "ver": 1,
    "vin_sz": 2,
    "vout_sz": 1,
    "lock_time": 0,
    "size": 123,
    "in": [
      {
        "prev_out": {
          "hash": "5a26baff403c678a8386a04800f82a693c12c9e5f8fc443492deb08e3cecbb15",
          "n": 0
        },
        "scriptSig": ""
      },
      {
        "prev_out": {
          "hash": "e74dfeed4131c14264807b4782f0a2b9a8a6413d1d3dd99fd85bd0bdf7cd7d02",
          "n": 0
        },
        "scriptSig": ""
      }
    ],
    "out": [
      {
        "value": "0.16185575",
        "scriptPubKey": "0 b19a7fe6634fd11c3867c272b7b28db0508f1139"
      }
    ]
  },
  "inputs": [
    {
      "index": 0,
      "partial_signatures": {},
      "final_script_witness": "3045022100b1a0b6e6444d46e3348be8ad6f59f70efc6370b9967ee8198042481443b09b0e02203cc77a87cc958b7e9dde16592d64eb08b48f35ab20f442e1d7453031f9ce4b7501 0226faf9bd354f27a539176ee5a7969127751abf6b46be2f1dd4d5aa72dbde130e",
      "witness_utxo": {
        "value": "0.04956665",
        "scriptPubKey": "0 df741e7638513c0582a754ac0eb20189a5f0d704"
      },
      "bip32_derivs": []
    },
    {
      "index": 1,
      "partial_signatures": {},
      "final_script_witness": "3045022100996c01e9799f4301886ea750585cbea142c956bd339b88c542280a294a214a8802204b0fed001a33ed0566ac3bb3cb2c6c479f6fada10f7275d36c9f35265140f07101 022c9a180435eb0c83f35b30ce9ab61e59f4c94cb1c1e09c9ba30d552e45d2aa79",
      "witness_utxo": {
        "value": "0.11229088",
        "scriptPubKey": "0 c6236ab9791ad86a26deb50bc9154ecd554bf306"
      },
      "bip32_derivs": []
    }
  ],
  "outputs": [
    {
      "bip32_derivs": []
    }
  ]
}}
```

**Comment by NicolasDorier** [comment]
mmmh so that's probably an issue either at HWI level or Ledger level.

**Comment by nopara73** [comment]
I think HWI just forwards the PSBT hexes and doesn't touch it, so it must be something with Ledger. IMO this is the biggest clue here: https://github.com/MetacoSA/NBitcoin/pull/888#issuecomment-662986538

On another important note. Since you seem to be reading this I'd like to take the opportunity and ask if you could merge https://github.com/MetacoSA/NBitcoin/pull/883 and release? I explained why it's important in slack yesterday.

**Comment by molnard** [comment]
Pinging @KhalilBellakrid @pollastri-pierre @llehmann-ledger @gagbo from Ledger (sorry if not relevant I was not sure who to tag). Can you take a look at the above problem? Can it be a firmware bug in the Ledger Nano S?

**Comment by NicolasDorier** [comment]
@molnard can you share the xpub so they can repro?

**Comment by molnard** [comment]
Yes, I can share, but I don't know how. The wallet is already created on the device by someone. IMO the issue can be repro by any wallet.

**Comment by nopara73** [comment]
Yeah, mnemonic is not necessary, it can be reproduced with any wallet. Anyhow if Ledger guys confirm that we aren't supposed to work with the `partial_signatures` then we can close this PR and the corresponding issue in NBitcoin.

**Comment by NicolasDorier** [comment]
@molnard should you close this one?

**Comment by molnard** [comment]
It is still not solved. We hacked it around by if the exception occurs then not include the prev tx-s in the PSBT so Ledger will give a warning with "Unverified inputs" but the user can bypass it. 

The question is.

- Can NBitcoin handle partial_signatures like this? If not then I guess this issue is a feature request. 
- If NBitcoin can handle partial_signatures, then why cannot finalize the below one? 
- If the below tx is invalid because the signatures are not correct, then this is a Ledger issue and I will open an issue there and close this.

Does this makes sense?

```
{{
  "fee": "0.00000178 BTC",
  "feeRate": "1 Sat/B",
  "tx": {
    "hash": "cb27378511910c2be4b5272af5bd18b2fd3b736821bc3b4d87c875923cf7b50f",
    "ver": 1,
    "vin_sz": 2,
    "vout_sz": 1,
    "lock_time": 0,
    "size": 123,
    "in": [
      {
        "prev_out": {
          "hash": "5a26baff403c678a8386a04800f82a693c12c9e5f8fc443492deb08e3cecbb15",
          "n": 0
        },
        "scriptSig": ""
      },
      {
        "prev_out": {
          "hash": "e74dfeed4131c14264807b4782f0a2b9a8a6413d1d3dd99fd85bd0bdf7cd7d02",
          "n": 0
        },
        "scriptSig": ""
      }
    ],
    "out": [
      {
        "value": "0.16185575",
        "scriptPubKey": "0 69a970f131b7044eca43256f8e1432c7963a7c2a"
      }
    ]
  },
  "inputs": [
    {
      "index": 0,
      "partial_signatures": {
        "0226faf9bd354f27a539176ee5a7969127751abf6b46be2f1dd4d5aa72dbde130e": "304402203e3d31604d16dbba97041bd57454822f9f96224eeb253cb9cb43f2925f7c360202203264b74572dc604093f2a15e7c66ca8d704b1f273fd00ef6c85873bacde62b1201"
      },
      "non_witness_utxo": {
        "hash": "5a26baff403c678a8386a04800f82a693c12c9e5f8fc443492deb08e3cecbb15",
        "ver": 1,
        "vin_sz": 1,
        "vout_sz": 1,
        "lock_time": 0,
        "size": 192,
        "in": [
          {
            "prev_out": {
              "hash": "ac65e533a94733184e61a71a1269c77775bca514edd285499590f3c763cb7a1b",
              "n": 2
            },
            "scriptSig": "",
            "witness": "30450221009173e79b361f54a3b80048726087008b431e4cf26b9271ce146689b1a910c73202205ec9088f0020a4929e14048d3179817b7d1e319dce4bf0495a154bf77128b7d101 0252d80564fbdf9e0bd6dd81ed191bf61ac97c43657e6f584f3454a02b7cc6042a"
          }
        ],
        "out": [
          {
            "value": "0.04956665",
            "scriptPubKey": "0 df741e7638513c0582a754ac0eb20189a5f0d704"
          }
        ]
      },
      "witness_utxo": {
        "value": "0.04956665",
        "scriptPubKey": "0 df741e7638513c0582a754ac0eb20189a5f0d704"
      },
      "bip32_derivs": [
        {
          "pubkey": "0226faf9bd354f27a539176ee5a7969127751abf6b46be2f1dd4d5aa72dbde130e",
          "master_fingerprint": "a573b895",
          "path": "84'/0'/0'/0/11"
        }
      ]
    },
    {
      "index": 1,
      "partial_signatures": {
        "022c9a180435eb0c83f35b30ce9ab61e59f4c94cb1c1e09c9ba30d552e45d2aa79": "304502210088f656da3f96b397a4fe721fe79c7f94c988f43309fc0faf292f07b9c3edfda9022033bf7c2375e4bb3a019ba3a4cbb3dcaf42ff9ea649702fd1c2c4deb0fbea24e901"
      },
      "non_witness_utxo": {
        "hash": "e74dfeed4131c14264807b4782f0a2b9a8a6413d1d3dd99fd85bd0bdf7cd7d02",
        "ver": 1,
        "vin_sz": 1,
        "vout_sz": 1,
        "lock_time": 1781441,
        "size": 82,
        "in": [
          {
            "prev_out": {
              "hash": "321bee4fc64563709b4ee01715b925179c104bc349d1eb84e7a138dcd044ef6c",
              "n": 2
            },
            "scriptSig": "",
            "sequence": 4294967294
          }
        ],
        "out": [
          {
            "value": "0.11229088",
            "scriptPubKey": "0 c6236ab9791ad86a26deb50bc9154ecd554bf306"
          }
        ]
      },
      "witness_utxo": {
        "value": "0.11229088",
        "scriptPubKey": "0 c6236ab9791ad86a26deb50bc9154ecd554bf306"
      },
      "bip32_derivs": [
        {
          "pubkey": "022c9a180435eb0c83f35b30ce9ab61e59f4c94cb1c1e09c9ba30d552e45d2aa79",
          "master_fingerprint": "a573b895",
          "path": "84'/0'/0'/0/10"
        }
      ]
    }
  ],
  "outputs": [
    {
      "bip32_derivs": [
        {
          "pubkey": "03d5b9fab45a1c0287350a6d4d9b8daf5a5ba74d475d3c0faf2a354651a249de89",
          "master_fingerprint": "a573b895",
          "path": "84'/0'/0'/0/12"
        }
      ]
    }
  ]
}}
```

**Comment by NicolasDorier** [comment]
@molnard NBitcoin can properly finalize if all signatures are in partialSigs. If there is an exception, it means the signature is not good.

Can you give me a repro of how I can repro this?

**Comment by molnard** [comment]
With Trezor 1.5.1 and HWI 1.2.1 -  the issue is gone.

**Pull request closed without merging**
