### PR TITLE
Add unit tests for Crypto Internals

### PR DESCRIPTION
**Pull request by bitcoinbrisbane**
Added unit tests around BitMath.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
sorry @bitcoinbrisbane for make you waiting, just saw you PR.

I see that BitMath is only used for IsPositivePowerOf2, is it not a better idea to remove the other methods instead of testing them ?

**Comment by bitcoinbrisbane** [comment]
Its ok,

I’ve just run code analysis and look for classes with low code coverage.  As the method where public, I just thought to add unit tests.

Either remove or make them private?

**Comment by NicolasDorier** [comment]
Yes, let's remove the code if we can and keep the test for the one we use.

**Comment by NicolasDorier** [comment]
@bitcoinbrisbane BitMath is certainly better as internal and without the method we don't use, can you update this PR or I do it ?

**Comment by bitcoinbrisbane** [comment]
Hi Nicolas,


I wont be able to until tomorrow night.


________________________________

**Comment by bitcoinbrisbane** [comment]
Sorry for the late response. I'm happy to change the access modifier to internal.

**Comment by NicolasDorier** [comment]
I'll accept the PR as now, however, I'll appreciate if you can remove unused code from NBitcoin like the methods in BitMath when you have time.

**Comment by bitcoinbrisbane** [comment]
Should we deprecate them first?

Sent from my iPhone

On 24 Sep 2015, at 2:35 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll accept the PR as now, however, I'll appreciate if you can remove unused code from NBitcoin like the methods in BitMath when you have time.

-

**Comment by NicolasDorier** [comment]
No, these are most likely not used, we can remove.

**Pull request merged**
