### PR TITLE
Implement TaprootBuilder and TaprootSpendInfo

### PR DESCRIPTION
**Pull request by joemphilips**
This is a prerequisite for #1141 
It introduce a logic for building tapscript tree.

* based on types with the same name in rust-bitcoin and bitcoind
  * https://github.com/rust-bitcoin/rust-bitcoin/blob/70eb92cc870b05bd57d5c8d400af8995581fcb9b/bitcoin/src/util/taproot.rs#L184
  * https://github.com/bitcoin/bitcoin/blob/f0c646f026e652082e798800136dc06c734fdab6/src/script/standard.h#L226

It is expected to be used in TransactionBuilder and (possibly in) PSBT.

### CODE REVIEW

**Comment by joemphilips** [comment]
Ready for review.
The failing test seems nothing to do with my change @NicolasDorier

**Comment by NicolasDorier** [comment]
Damn great job. Didn't review too deep, but I will use it very soon so I'll dog food.

**Comment by NicolasDorier** [comment]
Cool even stuff for parsing the tree

**Comment by NicolasDorier** [comment]
Ah I thought it was the taproot output descriptor stuff, but this is actually better. I am happy to get that finally here, I'll use it soon.

**Comment by joemphilips** [comment]
Descriptor is almost finished too.  I've been debugging some nasty bugs related to x-only pubkey.

**Pull request merged**
