### PR TITLE
BouncyCastle merged in the main project

### PR DESCRIPTION
**Pull request by andbene72**
Hi Nicolas,

following the previuos discussion, I have eliminated the necessity to have a separated bouncycastle DLL.
I have suppressed a CLS related warning but not 3 warning related to the use of soon obsolete method in Bouncycastle as in a future we have to fix these.

Also I ask you if is it the case that I insert a NOSERIALIZABLE conditional compilation symbol instead of these 
#if !(NETCF_1_0 || NETCF_2_0 || SILVERLIGHT || PORTABLE)
    [Serializable]
#endif

as increasing the number of platform (.NET Core, UWP) not supporting it let the directive become a bit long. The same for ICloneable.

For what I see supporting .NET Core compilation involve changes very similar to ones needed to support native UWP. My test project.json in the case you wish to do a look.

`{`
`  "buildOptions": { `
`    "compile": {`
`      "include": [ "**/*.cs", "../NBitcoin/**/*.cs", "../NBitcoin.Portable/TraceStub/**/*.cs", "../NBitcoin.Portable/System.Numerics/**/*.cs", "../NBitcoin.Portable/System.Net/**/*.cs" ],`
`      "exclude": ["../NBitcoin/obj/**/*.cs", "../NBitcoin/bin/**/*.cs", "../NBitcoin/**/*.partial.cs", "../NBitcoin/MedianFilter.cs" ]`
`    },`
`    "define": [ "PORTABLE", "USEBC" ]`
    
`  },`
`  "dependencies": {`
`    "NETStandard.Library": "1.6.0",`
`    "Newtonsoft.Json": "9.0.1"`
`  },`
`  "frameworks": {`
`    "netstandard1.6": {`
`      "imports": "dnxcore50"`
`    }`
`  },`
`  "version": "1.0.0-*"`
`}`

Have you ever measured the difference in performance between using a framework System.Security call versus using NBitcoin.BouncyCastle ?

### CODE REVIEW

**Comment by NicolasDorier** [comment]
wow cool, I'll take a look.
Yes I benchmarked long time ago and found out that System.Security calls are quicker.

**Comment by NicolasDorier** [comment]
Ah important: Can you add a commit to put every classes in the BouncyCastle namespace as internal ?

**Comment by NicolasDorier** [comment]
Also, I'm thinking doing the same for Newtonsoft, but last time I tried to strip off unused code in the library, I needed to rollback :(

**Comment by andbene72** [comment]
ECKey class in NBitcoin.Crypto expose in public methods classes from Bouncycastle. It is safe to mark it as internal ?

**Comment by NicolasDorier** [comment]
yes it is safe

**Comment by NicolasDorier** [comment]
very cool thanks a lot, I'll test, merge and make a release soon.

**Comment by NicolasDorier** [comment]
hey, I made a new version with that PR v3.0.0.38

**Comment by NicolasDorier** [comment]
Only Newtonsoft to get rid now...

**Comment by tom-corwin** [comment]
Hey @andbene72 and @NicolasDorier  , 

If you look at the NBitcoin port I'm working on for .NET Core, I have made it to where you do not have to use the `PORTABLE` or `USEBC` conditional compilation symbol, but rather a `NETCORE` one, just so you can use the added features of .NET Core over Portable et al. The only thing left to do is find a temporary workaround until .NET Core 1.1.0 is released with added `System.Net.Sockets.Socket` support, since there is no `.BeginSend`, `.EndSend`, `.BeginConnect`, `.EndConnect`, `.BeginAccept`, or `.EndAccept` support yet.

For comparison, [here is my project.json](https://github.com/tom-corwin/NBitcoin-NETCore/blob/master/Source/NBitcoin.NETCore/project.json), if you were interested in seeing how things are arranged. Keep in mind I am using the latest beta packages of the .NET Core.

**Comment by NicolasDorier** [comment]
can you pull my latest changes ? I just pushed a big change which include Newtonsoft in the binaries of Portable project instead of relying on a dll.

**Comment by tom-corwin** [comment]
I pulled it into my fork. Working on applying most of the changes to my project. I'm hoping to have a separate branch on my for that will have the NETCore version merged with the master branch of NBitcoin in the near future.

**Comment by NicolasDorier** [comment]
you should just fork NBitcoin, create a new branch, and work on this branch, and just rebase if master is moving.

**Comment by tom-corwin** [comment]
I'm planning on doing that after the port is at least buildable, since right now it is not due to a few errors.

**Pull request merged**
