### PR TITLE
[WIP] Partially signed transactions

### PR DESCRIPTION
**Pull request by lontivero**
Very first classes for PSBT.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
You read in my mind!

**Comment by NicolasDorier** [comment]
The tests are broken

**Comment by lontivero** [comment]
I pushed this garbage just as a way to say "hey, i will be working on this". It is not completed in any way, it doesn't have tests and the only test fails because i did it just to be able to execute the code.

**Comment by joemphilips** [comment]
What is the situation for this? I can take after you if you are too busy. @lontivero

**Comment by lontivero** [comment]
@joemphilips yes, take it please.

**Comment by joemphilips** [comment]
This PR must be closed #596 .

**Pull request closed without merging**
