### PR TITLE
Fix formatting (NBitcoin.Altcoins)

### PR DESCRIPTION
**Pull request by yahiheb**

### CODE REVIEW

**Comment by nopara73** [comment]
ReYahihebSharper

**Comment by NicolasDorier** [comment]
this one is tricky for me to review. (can't just check it is only whitespaces) and tests does not pass.

**Comment by yahiheb** [comment]
@nopara73 lol but I really like to see the code very clean :p.
@NicolasDorier I agree.
Should I break it into smaller PRs (6 or 7 files per PR) but they might still be big?
Or to avoid the review you can do it yourself. If you are using Visual Studio 2019, use `Alt + Enter` (Quick Actions)  on a line containing for ex `if(` and choose `Fix formatting` and then `Fix all occurrences in: Solution`.

**Comment by NicolasDorier** [comment]
Closing this one for inactivity. I don't think we have to format, we can do as we go. However, if we do, you can break in smaller pieces.

**Pull request closed without merging**
