### PR TITLE
prefer use ChainBase

### PR DESCRIPTION
**Pull request by micky53**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I agree it would make sense in theory. However, I plan to make `ChainBase` obsolete and remove it in a future version, so I prefer people do not use it directly. I have not found a single usecase where it was useful to have anything else than `ConcurrentChain`.

**Comment by micky53** [comment]
It's sad to hear this. I would like to implement my class derived from `ChainBase`, which will store the headers in the database and load them as needed. Thus, when you start the program, it will not be necessary to spend time reading from the disk more than 100 MB.

**Comment by NicolasDorier** [comment]
@micky53 that was my intention in the beginning. 

However clients of this class expect `GetBlock` to not fail or have any IO (need to be fast), so having it back by your own database would break lot's of assumptions.

A database backed version should have async functions, and probably another interface and another class. I don't know how a good interface would look like though, so if you have ideas, I am open to it.

You don't want 1 DB request per header though, it would kill perf. (`GetBlockAsync`)

**Comment by micky53** [comment]
I have no ideas. Cancel polmostechest.

**Pull request closed without merging**
