### PR TITLE
Add Network.NetworkType

### PR DESCRIPTION
**Pull request by bazooka70**
https://github.com/dgarage/NBXplorer/issues/45

Something like this?
All other alt coins should be updated as well...

### CODE REVIEW

**Comment by bazooka70** [comment]
Do you approve with the enum naming or should it be the same as ChainType? i.e.
Main, Test, Regtest?

```
NetworkType = enum
{
  Regtest,
  Main,
  Test
}
```

the above seems kind of sloppy I must say.

**Comment by NicolasDorier** [comment]
Same as ChainType is better, less chance we break stuff.

**Comment by bazooka70** [comment]
I would probably change both to
```
{
  Main,
  Testnet
  Regtest,    
}
```

It's up to you

**Comment by bazooka70** [comment]
I think its fine as is now

**Comment by NicolasDorier** [comment]
Will remove the EnsureRegistered from here. It is important to make it explicit as it register some stuff globally.

**Comment by bazooka70** [comment]
So now the `BCash.EnsureRegistered();` is no longer needed?
And used like ?
`var xnetwork = new NBXplorerNetworkProvider(NetworkType.Testnet).GetBCH();`

And in NBitcoin like this?
`Network _network1 = NBitcoin.Altcoins.BCash.Instance.Testnet;`
OR?
`Network _network2 = AltNetworkSets.BCash.Testnet;`

**Comment by NicolasDorier** [comment]
yes

**Pull request merged**
