### PR TITLE
Add rpc methods

### PR DESCRIPTION
**Pull request by lontivero**
Adds RPC methods:

* getblockchaininfo
* bumpfee

Modifies the RPC methods:

* sendtoaddress

Also, includes two commits for allowing to run the tests on Linux and OSX

### CODE REVIEW

**Comment by NicolasDorier** [comment]
you built on top of another branch than master

**Comment by lontivero** [comment]
No, I created the branch from master and then I cherrypicked two commits from the other PR and built on top of that. I can make a new PR from a new branch without cherrypicking commits if you have errors.

**Comment by NicolasDorier** [comment]
I mean can you limit this PR to what it says it does ?  The EnsureDownload stuff will conflict with your other PR if you don't.

**Comment by lontivero** [comment]
Done

**Pull request merged**
