### PR TITLE
Support mutinynet

### PR DESCRIPTION
**Pull request by Kukks**
This PR refactors Network and its Bitcoin networks, in that it pulls them to the NetworkSet class to reduce its coupling and make their instantiation similar to how every other network is created. It is IMO a much cleaner result.

Additioanlly, it adds support for MutinyNet, a custom signet network with 30s blocks and many covenant soft forks activated. Most of LN testing infra runs on Mutinynet, and is very useful.

### CODE REVIEW

**Comment by dangershony** [comment]
Didn't they shutdown the wallet?
https://blog.mutinywallet.com/mutiny-wallet-is-shutting-down/

**Comment by Kukks** [comment]
> Didn't they shutdown the wallet? [blog.mutinywallet.com/mutiny-wallet-is-shutting-down](https://blog.mutinywallet.com/mutiny-wallet-is-shutting-down/)

They did, but most of LN test infra runs on mutinynet so I'm hopeful the mutiny of mutiny will draw a line at their signet and keep it.

**Comment by dangershony** [comment]
Gotcha, actually its good to have a few testnets, perhaps at some point we'll add Angor's testnet as well.

**Comment by NicolasDorier** [comment]
There is some issues with the refactoring I believe, a test randomly failed.

```
[xUnit.net 00:00:00.77]     CanBuildSegwitP2SHMultisigTransactions [FAIL]
  Failed CanBuildSegwitP2SHMultisigTransactions [58 ms]
  Error Message:
   System.InvalidOperationException : The network Main is already registered
  Stack Trace:
     at NBitcoin.Network.Register(NetworkBuilder builder) in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Network.cs:line 855
   at NBitcoin.NetworkBuilder.BuildAndRegister() in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/NetworkBuilder.cs:line 166
   at NBitcoin.Bitcoin.CreateMainnet() in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Bitcoin.Mainnet.cs:line 96
   at NBitcoin.Bitcoin.get_Mainnet() in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Bitcoin.Mainnet.cs:line 8
   at NBitcoin.Bitcoin.CreateTestnet() in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Bitcoin.Testnet.cs:line 29
   at NBitcoin.Bitcoin.CreateRegtest() in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Bitcoin.Regtest.cs:line 28
   at NBitcoin.Bitcoin.get_Regtest() in /home/runner/work/NBitcoin/NBitcoin/NBitcoin/Bitcoin.Regtest.cs:line 9
   at NBitcoin.Tests.NodeBuilderEx.Create(NodeDownloadData nodeDownloadData, String caller) in /home/runner/work/NBitcoin/NBitcoin/NBitcoin.Tests/NodeBuilderEx.cs:line 81
   at NBitcoin.Tests.NodeBuilderEx.Create(String caller) in /home/runner/work/NBitcoin/NBitcoin/NBitcoin.Tests/NodeBuilderEx.cs:line 72
   at NBitcoin.Tests.sample_tests.CanBuildSegwitP2SHMultisigTransactions() in /home/runner/work/NBitcoin/NBitcoin/NBitcoin.Tests/sample_tests.cs:line 196
```

**Comment by chrisguida** [comment]
🎉

**Pull request merged**
