### PR TITLE
Set max incoming connections

### PR DESCRIPTION
**Pull request by dangershony**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I think that backlog != maxconnection, can you write a simple unit test to check it ? But I may be wrong.

**Comment by dangershony** [comment]
@NicolasDorier how about this?
I wasn't sure how FindOrConnect should handle the max limit though.

**Comment by NicolasDorier** [comment]
@dangershony I am not sure FindOrConnect make sense at all.
Find without connection would.

I think you can close the connection even before processing any message, in the socket Accept loop.

**Comment by dangershony** [comment]
Yeah its odd as that would create an outbound connection and the list should only have inbound, 
I will change it no problem.

I was thinking on closing the connection earlier that means I'll have to call the method Utils.SafeCloseSocket(Socket) rather then the standard Node functionality

**Comment by dangershony** [comment]
it seems FindOrConnect is used for testing so I will ignore it for now, unless it has a production purpose.

**Comment by dangershony** [comment]
Can you also bump the nuget build?

**Comment by NicolasDorier** [comment]
do when going back home tomorrow

**Comment by dangershony** [comment]
Thanks I will update the fullnode

**Pull request merged**
