### PR TITLE
Fix special case with empty filters

### PR DESCRIPTION
**Pull request by lontivero**
This fixes the filters matching for the special case where the filter is empty. Querying an empty filter must result in false result but it was returning true.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
can you remove the formating change?

**Comment by nopara73** [comment]
IMO the formatting is good. A better view of the PR: https://github.com/MetacoSA/NBitcoin/pull/776/files?w=1

**Comment by nopara73** [comment]
Also it's strange, I don't see any whitespace change.

**Comment by lontivero** [comment]
oh fuck! I forced the push because git added the windows ending CRLF to each line. Sorry

**Comment by lontivero** [comment]
Are you going to modify this PR? Or should I add your commit and push it on top of the forced commit?

**Pull request merged**
