### PR TITLE
Add getblockstats to RPCClient

### LINKED ISSUE #1029: Missing RPC getblockstats
Any plans to add this to the RPC client?

See https://bitcoincore.org/en/doc/0.17.0/rpc/blockchain/getblockstats/

### PR DESCRIPTION
**Pull request by bezysoftware**
Resolves #1029

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Thanks, can you add one test?

**Comment by bezysoftware** [comment]
> 
> 
> Thanks, can you add one test? This help to spot when code break because of breaking change in new release of nodes.

Can you help me with the setup of the test? When I try to call the method I get "Can't read undo data from disk" error. I tried running "bitcoin-qt" as described in the `RPCClientTests.cs` file but I get the same error.

**Comment by NicolasDorier** [comment]
@bezysoftware just look at all the RPC tests that already exists in NBitcoin and do the same (example `CanGetBlockFromRPC`)

**Comment by bezysoftware** [comment]
@NicolasDorier turns out I cannot run the `getblockstats` on the genesis block but must generate at least one extra, the above error was coming as a result of the RPC call

**Pull request merged**
