### PR TITLE
Test ECDSASignature.ToDER is Bip66 compatible

### PR DESCRIPTION
**Pull request by DanGould**
demonstrates #773 is resolved. ECDSASignature.ToDER() encodes only positive exponents.

-- 

To get the tests to appear and build on VS Mac, I had to switch around the order of TargetFramework Dependencies:
```diff
-         <TargetFrameworks>net461;netcoreapp3.1</TargetFrameworks>
+         <TargetFrameworks>netcoreapp3.1;net461</TargetFrameworks>
```

If this doesn't cause any other issue, I will create a separate pull request to resolve this

### CODE REVIEW

**Comment by DanGould** [comment]
I think this is failing because the test environment is using BouncyCastle ECDSASignature still, which should fail

**Comment by NicolasDorier** [comment]
@DanGould can you just remove this test for netframework? That's fine, we don't need to fix it.
Then I can merge this.

**Comment by NicolasDorier** [comment]
Also don't use separate file, put it somewhere else where there is tests on sigs

**Comment by NicolasDorier** [comment]
Also you can switch both to fix on mac in this PR.

**Comment by NicolasDorier** [comment]
You added the tests in a `!HAS_SPAN` section, should be the reverse.

**Comment by DanGould** [comment]
thanks for your patience

**Pull request merged**
